apiVersion: v2
name: spotfire-terrservice
description: A Helm chart for SpotfireÂ® Enterprise Runtime for R - Server Edition

type: application

version: 3.0.1

appVersion: "1.24.0"

kubeVersion: ">=1.24.0-0"

home: https://github.com/spotfiresoftware/spotfire-cloud-deployment-kit
sources:
 - https://github.com/spotfiresoftware/spotfire-cloud-deployment-kit

keywords:
  - spotfire
  - terr
  - analytics
  - data science
  - data functions

dependencies:
  - name: spotfire-common
    repository: file://../spotfire-common
    version: 3.0.1

annotations:
  license: Apache 2.0
  licenseUrl: https://github.com/spotfiresoftware/spotfire-cloud-deployment-kit/blob/main/LICENSE
