apiVersion: v2
name: spotfire-terrservice
description: A Helm chart for TIBCOÂ® Enterprise Runtime for R - Server Edition

type: application

version: 0.1.2

appVersion: "1.12.0"

home: https://github.com/TIBCO/Spotfire-cloud-deployment-kit
sources:
 - https://github.com/TIBCO/Spotfire-cloud-deployment-kit

keywords:
  - spotfire
  - terr
  - analytics
  - data science
  - data functions

dependencies:
  - name: spotfire-common
    repository: file://../spotfire-common
    version: 0.1.2

annotations:
  license: Apache 2.0
  licenseUrl: https://github.com/TIBCOSoftware/spotfire-cloud-deployment-kit/blob/main/LICENSE
