apiVersion: v2
name: spotfire-common
description: A Helm chart with common templates used in TIBCO Spotfire charts.
type: library
version: 0.1.1

home: https://github.com/TIBCO/Spotfire-cloud-deployment-kit
sources:
 - https://github.com/TIBCO/Spotfire-cloud-deployment-kit

annotations:
  license: Apache 2.0
  licenseUrl: https://github.com/TIBCOSoftware/spotfire-cloud-deployment-kit/blob/main/LICENSE
