apiVersion: v2
name: spotfire-automationservices
description: A Helm chart for Spotfire Automation Services.

type: application

version: 3.0.2

appVersion: "14.7.0-HF-002"

kubeVersion: ">=1.24.0-0"

home: https://github.com/spotfiresoftware/spotfire-cloud-deployment-kit
sources:
 - https://github.com/spotfiresoftware/spotfire-cloud-deployment-kit

keywords:
  - spotfire
  - automation
  - analytics
  - data visualization
  - workflow

dependencies:
  - name: spotfire-common
    repository: file://../spotfire-common
    version: 3.0.2

annotations:
  license: Apache 2.0
  licenseUrl: https://github.com/spotfiresoftware/spotfire-cloud-deployment-kit/blob/main/LICENSE
