apiVersion: v2
name: spotfire-webplayer
description: A Helm chart for Spotfire Web Player.

type: application

version: 3.0.1

appVersion: "14.7.0-HF-001"

kubeVersion: ">=1.24.0-0"

home: 'https://github.com/spotfiresoftware/spotfire-cloud-deployment-kit'

keywords:
  - spotfire
  - webplayer
  - analytics
  - data science
  - data visualization

dependencies:
  - name: spotfire-common
    repository: file://../spotfire-common
    version: 3.0.1

annotations:
  license: Apache 2.0
  licenseurl: https://github.com/spotfiresoftware/spotfire-cloud-deployment-kit/blob/main/LICENSE
